model_list:
  - model_name: bibliotecario-generation
    litellm_params:
      model: os.environ/LLAMA_GENERATION_MODEL
      api_base: os.environ/LLAMA_GENERATION_BASE_URL
      api_key: os.environ/LLAMA_GENERATION_API_KEY
litellm_settings:
  set_verbose: false
  json_logs: true
  turn_off_message_logging: true
  request_timeout: 15
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
