import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';

test.use({ trace: 'off' });
test('real document upload, revisions, preview, review and deletion', async ({ page }, info) => {
  test.skip(!process.env.BIB_E2E_CREDENTIALS, 'Requires Compose and a local account file');
  test.setTimeout(90000);
  const account = JSON.parse(readFileSync(process.env.BIB_E2E_CREDENTIALS!, 'utf8'));
  const origin = process.env.BIB_E2E_ORIGIN || 'http://localhost:3000';
  const name = `browser-${info.project.name}-${Date.now()}.md`;
  const content = '# Documento sintetico\n\nTexto revisable.\n\n| A | B |\n| --- | --- |\n| Uno | Dos |\n';
  await page.goto(`${origin}/login`);
  await page.getByLabel('Usuario', { exact: true }).fill(account.username);
  await page.getByLabel('Contrasena').fill(account.password);
  await page.getByRole('button', { name: 'Entrar' }).click();
  await expect(page).toHaveURL(`${origin}/admin`);
  await page.getByRole('link', { name: 'Documentos', exact: true }).click();
  await page.locator('input[type=file]').first().setInputFiles({ name, mimeType: 'text/markdown', buffer: Buffer.from(content) });
  await expect(page.getByLabel('Markdown')).toHaveValue(content, { timeout: 30000 });
  await page.getByLabel('Autor', { exact: true }).fill('Autor sintetico');
  await page.getByLabel('Etiquetas').pressSequentially('uno, dos');
  await expect(page.getByLabel('Etiquetas')).toHaveValue('uno, dos');
  await page.getByLabel('Markdown').fill(content + '\nTexto editado.\n<script>window.untrustedDocument=true</script>\n![Imagen remota](https://example.invalid/image.png)\n');
  await page.getByRole('button', { name: 'Guardar revision', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Revision guardada.');
  await expect(page.getByLabel('Revision normalizada').locator('option')).toHaveCount(2);
  await page.getByRole('button', { name: 'Vista previa', exact: true }).click();
  await expect(page.locator('.markdown-preview table')).toBeVisible();
  await expect(page.locator('.markdown-preview script, .markdown-preview img')).toHaveCount(0);
  expect(await page.evaluate(() => (window as Window & { untrustedDocument?: boolean }).untrustedDocument)).toBeUndefined();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: info.outputPath('document-preview.png'), fullPage: true });
  await page.getByRole('button', { name: 'Procedencia', exact: true }).click();
  await expect(page.getByText('Edicion manual', { exact: true }).first()).toBeVisible();
  await page.getByLabel('Revision normalizada').selectOption({ label: 'Revision 1 - conversion' });
  await expect(page.getByLabel('Autor', { exact: true })).toHaveValue('');
  await expect(page.getByRole('button', { name: 'Guardar revision', exact: true })).toBeDisabled();
  await page.getByLabel('Revision normalizada').selectOption({ label: 'Revision 2 - editada' });
  await expect(page.getByLabel('Autor', { exact: true })).toHaveValue('Autor sintetico');
  await page.getByRole('button', { name: 'Marcar revisado', exact: true }).click();
  await expect(page.getByText('Revisado', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Eliminar documento', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'Eliminar documento', exact: true }).click();
  await page.getByLabel('Confirmar titulo').fill(name);
  await page.getByRole('button', { name: 'Eliminar', exact: true }).click();
  await expect(page.getByRole('button', { name, exact: true })).toHaveCount(0, { timeout: 30000 });
  await page.getByRole('link', { name: 'Trabajos', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Trabajos de ingesta' })).toBeVisible();
  await page.screenshot({ path: info.outputPath('jobs.png'), fullPage: true });
  await page.getByRole('button', { name: 'Cerrar sesion' }).click();
  await expect(page).toHaveURL(`${origin}/login`);
});
